### ISSUE TITLE
Bug with 2.0.2

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-BulkEdit#5]
On 2.0.2 with current master version of this module, batch edits seems to work but there is no modification to items. 

related to #4

**Comment by dukecld** [comment]
installed bulkedit last week.  batch edits work for manually selected items; but for select all option, there is no modification to items.

**Comment by pprw** [comment]
I tested again (for displacing value). It is not working. here is the trace:

```

Doctrine\DBAL\Exception\UniqueConstraintViolationException
An exception occurred while executing 'INSERT INTO resource_template_property (alternate_label, alternate_comment, position, data_type, is_required, is_private, resource_template_id, property_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params ["Titre", null, 1, null, 0, 0, 5, 1]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5-1' for key 'UNIQ_4689E2F116131EA549213EC'

Détails :

PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5-1' for key 'UNIQ_4689E2F116131EA549213EC' in /sites/ehp-ahpnum/www/web_main/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
Stack trace:
#0 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute(NULL)
#1 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(153): Doctrine\DBAL\Driver\PDOStatement->execute(NULL)
#2 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(285): Doctrine\DBAL\Statement->execute()
#3 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1073): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#4 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(386): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(359): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /sites/ehp-ahpnum/www/web_main/application/src/Api/Adapter/AbstractEntityAdapter.php(369): Doctrine\ORM\EntityManager->flush()
#7 /sites/ehp-ahpnum/www/web_main/application/src/Api/Manager.php(233): Omeka\Api\Adapter\AbstractEntityAdapter->update(Object(Omeka\Api\Request))
#8 /sites/ehp-ahpnum/www/web_main/application/src/Api/Manager.php(136): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#9 /sites/ehp-ahpnum/www/web_main/application/src/Mvc/Controller/Plugin/Api.php(152): Omeka\Api\Manager->update('items', '17426', Array, Array, Array)
#10 /sites/ehp-ahpnum/www/web_main/modules/BulkEdit/Module.php(507): Omeka\Mvc\Controller\Plugin\Api->update('items', '17426', Array, Array, Array)
#11 /sites/ehp-ahpnum/www/web_main/modules/BulkEdit/Module.php(307): BulkEdit\Module->updateValues(Object(Omeka\Api\Adapter\ItemAdapter), Array, Array)
#12 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): BulkEdit\Module->handleResourceBatchUpdatePost(Object(Zend\EventManager\Event))
#13 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\EventManager\Event))
#14 /sites/ehp-ahpnum/www/web_main/application/src/Api/Manager.php(323): Zend\EventManager\EventManager->triggerEvent(Object(Zend\EventManager\Event))
#15 /sites/ehp-ahpnum/www/web_main/application/src/Api/Manager.php(269): Omeka\Api\Manager->finalize(Object(Omeka\Api\Adapter\ItemAdapter), Object(Omeka\Api\Request), Object(Omeka\Api\Response))
#16 /sites/ehp-ahpnum/www/web_main/application/src/Api/Manager.php(146): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#17 /sites/ehp-ahpnum/www/web_main/application/src/Mvc/Controller/Plugin/Api.php(171): Omeka\Api\Manager->batchUpdate('items', Array, Array, Array)
#18 /sites/ehp-ahpnum/www/web_main/application/src/Controller/Admin/ItemController.php(286): Omeka\Mvc\Controller\Plugin\Api->batchUpdate('items', Array, Array, Array)
#19 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\Admin\ItemController->batchEditAction()
#20 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#21 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#23 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#24 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#25 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#26 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#27 /sites/ehp-ahpnum/www/web_main/index.php(21): Zend\Mvc\Application->run()
#28 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5-1' for key 'UNIQ_4689E2F116131EA549213EC' in /sites/ehp-ahpnum/www/web_main/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119
Stack trace:
#0 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(153): Doctrine\DBAL\Driver\PDOStatement->execute(NULL)
#1 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(285): Doctrine\DBAL\Statement->execute()
#2 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1073): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#3 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(386): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#4 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(359): Doctrine\ORM\UnitOfWork->commit(NULL)
#5 /sites/ehp-ahpnum/www/web_main/application/src/Api/Adapter/AbstractEntityAdapter.php(369): Doctrine\ORM\EntityManager->flush()
#6 /sites/ehp-ahpnum/www/web_main/application/src/Api/Manager.php(233): Omeka\Api\Adapter\AbstractEntityAdapter->update(Object(Omeka\Api\Request))
#7 /sites/ehp-ahpnum/www/web_main/application/src/Api/Manager.php(136): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#8 /sites/ehp-ahpnum/www/web_main/application/src/Mvc/Controller/Plugin/Api.php(152): Omeka\Api\Manager->update('items', '17426', Array, Array, Array)
#9 /sites/ehp-ahpnum/www/web_main/modules/BulkEdit/Module.php(507): Omeka\Mvc\Controller\Plugin\Api->update('items', '17426', Array, Array, Array)
#10 /sites/ehp-ahpnum/www/web_main/modules/BulkEdit/Module.php(307): BulkEdit\Module->updateValues(Object(Omeka\Api\Adapter\ItemAdapter), Array, Array)
#11 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): BulkEdit\Module->handleResourceBatchUpdatePost(Object(Zend\EventManager\Event))
#12 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\EventManager\Event))
#13 /sites/ehp-ahpnum/www/web_main/application/src/Api/Manager.php(323): Zend\EventManager\EventManager->triggerEvent(Object(Zend\EventManager\Event))
#14 /sites/ehp-ahpnum/www/web_main/application/src/Api/Manager.php(269): Omeka\Api\Manager->finalize(Object(Omeka\Api\Adapter\ItemAdapter), Object(Omeka\Api\Request), Object(Omeka\Api\Response))
#15 /sites/ehp-ahpnum/www/web_main/application/src/Api/Manager.php(146): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#16 /sites/ehp-ahpnum/www/web_main/application/src/Mvc/Controller/Plugin/Api.php(171): Omeka\Api\Manager->batchUpdate('items', Array, Array, Array)
#17 /sites/ehp-ahpnum/www/web_main/application/src/Controller/Admin/ItemController.php(286): Omeka\Mvc\Controller\Plugin\Api->batchUpdate('items', Array, Array, Array)
#18 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\Admin\ItemController->batchEditAction()
#19 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#20 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#22 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#23 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#24 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#25 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#26 /sites/ehp-ahpnum/www/web_main/index.php(21): Zend\Mvc\Application->run()
#27 {main}

Next Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO resource_template_property (alternate_label, alternate_comment, position, data_type, is_required, is_private, resource_template_id, property_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params ["Titre", null, 1, null, 0, 0, 5, 1]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5-1' for key 'UNIQ_4689E2F116131EA549213EC' in /sites/ehp-ahpnum/www/web_main/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:55
Stack trace:
#0 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(169): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'An exception oc...')
#2 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(162): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO res...', Array)
#3 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(285): Doctrine\DBAL\Statement->execute()
#4 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1073): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#5 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(386): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#6 /sites/ehp-ahpnum/www/web_main/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(359): Doctrine\ORM\UnitOfWork->commit(NULL)
#7 /sites/ehp-ahpnum/www/web_main/application/src/Api/Adapter/AbstractEntityAdapter.php(369): Doctrine\ORM\EntityManager->flush()
#8 /sites/ehp-ahpnum/www/web_main/application/src/Api/Manager.php(233): Omeka\Api\Adapter\AbstractEntityAdapter->update(Object(Omeka\Api\Request))
#9 /sites/ehp-ahpnum/www/web_main/application/src/Api/Manager.php(136): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#10 /sites/ehp-ahpnum/www/web_main/application/src/Mvc/Controller/Plugin/Api.php(152): Omeka\Api\Manager->update('items', '17426', Array, Array, Array)
#11 /sites/ehp-ahpnum/www/web_main/modules/BulkEdit/Module.php(507): Omeka\Mvc\Controller\Plugin\Api->update('items', '17426', Array, Array, Array)
#12 /sites/ehp-ahpnum/www/web_main/modules/BulkEdit/Module.php(307): BulkEdit\Module->updateValues(Object(Omeka\Api\Adapter\ItemAdapter), Array, Array)
#13 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): BulkEdit\Module->handleResourceBatchUpdatePost(Object(Zend\EventManager\Event))
#14 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\EventManager\Event))
#15 /sites/ehp-ahpnum/www/web_main/application/src/Api/Manager.php(323): Zend\EventManager\EventManager->triggerEvent(Object(Zend\EventManager\Event))
#16 /sites/ehp-ahpnum/www/web_main/application/src/Api/Manager.php(269): Omeka\Api\Manager->finalize(Object(Omeka\Api\Adapter\ItemAdapter), Object(Omeka\Api\Request), Object(Omeka\Api\Response))
#17 /sites/ehp-ahpnum/www/web_main/application/src/Api/Manager.php(146): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#18 /sites/ehp-ahpnum/www/web_main/application/src/Mvc/Controller/Plugin/Api.php(171): Omeka\Api\Manager->batchUpdate('items', Array, Array, Array)
#19 /sites/ehp-ahpnum/www/web_main/application/src/Controller/Admin/ItemController.php(286): Omeka\Mvc\Controller\Plugin\Api->batchUpdate('items', Array, Array, Array)
#20 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\Admin\ItemController->batchEditAction()
#21 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#22 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#23 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#24 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#25 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#26 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#27 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#28 /sites/ehp-ahpnum/www/web_main/index.php(21): Zend\Mvc\Application->run()
#29 {main}

```

**Comment by pprw** [comment]
Any news about this?

**Comment by Daniel-KM** [comment]
Probably fixed in last versions.
